### ISSUE TITLE
pcgc_sumstats_creator.py : Error after removing "because they have different alleles in plink and MAF files"

### ISSUE THREAD

**Issue by sarah-n-wright** [omerwe/S-PCGC#4]
When a SNP with different alleles in the plink and MAF files are present they are successfully removed via:
```
is_consistent_snp = (df_maf[allele1_col] == df_bim['a1']) & (df_maf[allele0_col] == df_bim['a0'])
is_consistent_snp = is_consistent_snp | (df_maf[allele1_col] == df_bim['a0']) & (df_maf[allele0_col] == df_bim['a1'])
if not np.all(is_consistent_snp):
     logging.info('%d SNPs will be removed because they have different alleles in plink and MAF files'%(np.sum(~is_consistent_snp)))
     df_maf = df_maf.loc[is_consistent_snp]
     df_bim = df_bim.loc[is_consistent_snp]
```
However, this produces an error later in the code due to a size mismatch. 
```
0: Traceback (most recent call last):
0:   File "path/S-PCGC/pcgc_sumstats_creator.py", line 593, in <module>
0:     sumstats_creator.compute_all_sumstats(args.chunk_size)
0:   File "path/S-PCGC/pcgc_sumstats_creator.py", line 271, in compute_all_sumstats
0:     self.set_locus(snp1, snp2)
0:   File "path/S-PCGC/pcgc_sumstats_creator.py", line 318, in set_locus
0:     snp_maf = self.mafs[snp1+j]
0:   File "path/lib/python3.8/site-packages/pandas/core/series.py", line 879, in __getitem__
0:     return self._values[key]
0: IndexError: index 44269 is out of bounds for axis 0 with size 44269
```
If I force removal of additional SNPs, the index at which the error occurs reduces by a corresponding interval which leads me to believe this is what causes the problem. E.g. I forced removal of 2 additional SNPs the error becomes. 
```
IndexError: index 44267 is out of bounds for axis 0 with size 44267
```
I am able to get around this by identifying the mismatched SNPs and removing them from my `good_snps.txt` for now

**Comment by omerwe** [comment]
Hi, thanks for the bug report. I've pushed a fix to the GitHub repo, can you please git pull and retry?

Thanks,

Omer

**Comment by sarah-n-wright** [comment]
I am now receiving a different error:
```
Traceback (most recent call last):
0:   File "path/Git/S-PCGC/pcgc_sumstats_creator.py", line 590, in <module>
0:     sumstats_creator = PCGC_Sumstats(args)
0:   File "path/Git/S-PCGC/pcgc_sumstats_creator.py", line 75, in __init__
0:     self.bfile, df_pheno, df_maf, self.num_snps, self.sample_size = self.read_plink(args, df_pheno, df_maf)
0:   File "path/Git/S-PCGC/pcgc_sumstats_creator.py", line 530, in read_plink
0:     assert (df_pheno.index == df_fam.index).all()
0:   File "path/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 123, in cmp_method
0:     raise ValueError("Lengths must match to compare")
0: ValueError: Lengths must match to compare
```

**Comment by omerwe** [comment]
Thanks again. I fixed another bug, can you please git pull and retry?

**Comment by sarah-n-wright** [comment]
New fix is working :)
